# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JkMh5t_qD0wdGGDnYt9X34ROFt-o2Rxv
"""

import pandas as pd
df = pd.read_csv("новая табл11.csv")
df.head()

df_na = {col: list(pd.isna(df[col])).count(True) for col in cols}
df_na

df.dtypes

fan_df = df.loc[df["Fanclub Name"] != "-"]
fan_num = fan_df.shape[0]
nfan_df = df.loc[df["Fanclub Name"] == "-"]
nfan_num = nfan_df.shape[0]
fan_pie = pd.DataFrame({"": [fan_num, nfan_num]},
                       index=["Have", "Don't"])
fan_pie.plot.pie(y="",
                 colors=["g", "b"],
                 autopct="%.1f",
                 fontsize=10,
                 figsize=(5, 5));

act_df = df.loc[df["Active"] == "Yes"]
act_num = act_df.shape[0]
nact_df = df.loc[df["Active"] == "No"]
nact_num = nact_df.shape[0]
act_pie = pd.DataFrame({"": [act_num, nact_num]},
                       index=["Yes", "No"])
act_pie.plot.pie(y="",
                 colors=["c", "m"],
                 autopct="%.1f",
                 fontsize=10,
                 figsize=(5, 5));

male_df = df.loc[df["Gender"] == "M"]
m_num = male_df.shape[0]
fem_df = df.loc[df["Gender"] == "F"]
f_num = fem_df.shape[0]
age_pie = pd.DataFrame({"": [m_num, f_num]},
                       index=["M", "F"])
age_pie.plot.pie(y="",
                 colors=["c", "m"],
                 autopct="%.1f",
                 fontsize=10,
                 figsize=(5, 5));

import operator
company_data = {comp: df["Company"].to_list().count(comp) for comp in set(df["Company"])}
company_data=sorted(company_data.items(), key=operator.itemgetter(0))
company_data=dict(company_data)
del_data=[]
for i in company_data: #обрезаем редкие значения
  if company_data[i]<5: 
   del_data.append(i)
for j in del_data:
  del company_data[j]
import matplotlib.pyplot as plt
comp_df = pd.DataFrame.from_dict(data=company_data, orient="index", columns=["Company"])
fig, axes = plt.subplots(nrows=1, ncols=1)
comp_df.plot.barh(ax=axes, subplots = True, figsize=(12, 5));

fe_df = df.loc[(df["Company"] == "SM") & (df["Gender"] == "M")]
fe_num = fe_df.shape[0]
me_df = df.loc[(df["Company"] == "SM") & (df["Gender"] == "F")]
me_num = me_df.shape[0]
age_pie = pd.DataFrame({"": [me_num, fe_num]},
                       index=["M", "F"])
age_pie.plot.pie(y="",
                 colors=["c", "m"],
                 autopct="%.1f",
                 fontsize=10,
                 figsize=(5, 5));

import operator
members_data = {memb: df["Members"].to_list().count(memb) for memb in set(df["Members"])}
members_data=sorted(members_data.items(), key=operator.itemgetter(0))
members_data=dict(members_data)
del_data=[]
for i in members_data: #обрезаем редкие значения
  if members_data[i]<5: 
   del_data.append(i)
for j in del_data:
  del members_data[j]
import matplotlib.pyplot as plt
comp_df = pd.DataFrame.from_dict(data=members_data, orient="index", columns=["Number"])
fig, axes = plt.subplots(nrows=1, ncols=1)
comp_df.plot.barh(ax=axes, subplots = True, figsize=(12, 5));

from datetime import datetime
import math
import operator
dates = df.Debut
dates_list = []
num = 0
for i in dates:  #вычленяем год из строки
  if type(i) == str and i !="-":
   i = i[6:]
  dates_list.append(i)
  num = num+1
dates_list=sorted(dates_list)
date_data = {age: dates_list.count(age) for age in (dates_list)}
import matplotlib.pyplot as plt
age_df = pd.DataFrame.from_dict(data=date_data, orient="index", columns=["Number"])
age_df.plot();

ch_df = df.loc[df["Members"] != df["Orig. Memb."]]
ch_num = ch_df.shape[0]
nch_df = df.loc[df["Members"] == df["Orig. Memb."]]
nch_num = nch_df.shape[0]
ch_pie = pd.DataFrame({"": [ch_num, nch_num]},
                       index=["Changed", "No changes"])
ch_pie.plot.pie(y="",
                 colors=["y", "c"],
                 autopct="%.1f",
                 fontsize=10,
                 figsize=(5, 5));

from datetime import datetime
import math
import operator
dates = df.disband
dates_list = []
num = 0
for i in dates: #вычленяем год из строки
  if i !="0":
   i = i[6:]
   dates_list.append(i)
  num = num+1
dates_list=sorted(dates_list)
date_data = {age: dates_list.count(age) for age in (dates_list)}
import matplotlib.pyplot as plt
age_df = pd.DataFrame.from_dict(data=date_data, orient="index", columns=["Number"])
age_df.plot();

from datetime import datetime
import math
import operator
dates = df.Debut
debut_list = []
num = 0
for i in dates: #вычленяем год из строки
  if type(i) == str and i !="-":
   i = i[6:]
  debut_list.append(i)
  num = num+1
dates2 = df.disband
disband_list = []
num = 0
for j in dates2:
  if  j =="0":
    j="2021"
  else:
    j = j[6:]
  disband_list.append(j)
  num = num+1
old_list=[]
for k in range (0,num):
  l=int(disband_list[k])-int(debut_list[k])
  old_list.append(l)

import operator
age_data = {memb: old_list.count(memb) for memb in set(old_list)}
age_data=dict(age_data)
del_data=[]
for i in age_data:
  if age_data[i]<5: 
   del_data.append(i)
for j in del_data:
  del age_data[j]
import matplotlib.pyplot as plt
comp_df = pd.DataFrame.from_dict(data=age_data, orient="index", columns=["Age"])
fig, axes = plt.subplots(nrows=1, ncols=1)
comp_df.plot.barh(ax=axes, subplots = True, figsize=(12, 5));